name: Check CMake Configure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cmake-configure:
    runs-on: ubuntu-latest
    env:
      FW_TARGETS: "titan test_pwm test_spi test_usart test_oscilloscope"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Run CMake configure
        shell: bash
        run: |
          cmake -S src -B src/build

      - name: Build all targets
        shell: bash
        run: |
          cd src/build/
          for target in $FW_TARGETS; do
            echo "Building ${target}.elf"
            make "${target}.elf"
          done
          cd ../../
          gcc -std=c18 -Wall -Wextra ./src/internal/alloc.c ./test/test_alloc.c -o src/build/test_alloc || { echo "Compile test_alloc failed"; exit 21; }
          echo "Built target test_alloc"